name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        run: yarn
        with:
          command: "http-server -p 8000"
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
        with:
          command: "yarn test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}